version: "3.9"

services:
  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8080:8080"

  backend:
    container_name: backend-dev
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile.dev
    volumes:
      - "./backend:/code"
    ports:
      - "5000:5000"
